import {useMemo,useState} from 'react'
import './founders.css'
const profiles={
'Anooshka Soham Bathwal':{linkedin:'https://in.linkedin.com/in/anooshkasohambathwal',photo:'https://dhanvesttor.com/wp-content/uploads/2025/02/Anooshka-Soham-Bathwal-CEO-Founder-of-Dhanvesttor.jpg',company:'Dhanvesttor',role:'Founder & CEO',bio:'Founder & CEO of Dhanvesttor, a Kolkata-based wealth-management firm focused on making women more confident in finance.'},
'Gaurav Jalan':{linkedin:'https://in.linkedin.com/in/gauravjalan',photo:'https://cdn.mpokket.in/leadership_2_3d8f843f31.png',company:'mPokket',role:'Founder & CEO',bio:'Founder & CEO of mPokket, a Kolkata-based fintech platform.'},
'Prabir Sarkar':{linkedin:'https://www.linkedin.com/search/results/people/?keywords=Prabir%20Sarkar%20DSMenu',photo:'https://unavatar.io/https://www.linkedin.com/in/prabirsarkar/',company:'DSMenu',role:'Founder',bio:'Founder of DSMenu, a Kolkata-based digital-menu and signage SaaS platform.'},
'Ranodeep Saha':{linkedin:'https://in.linkedin.com/in/ranodeep-saha-rareplanet',photo:'https://alumni.wbut.ac.in/assets/img/testimonials/RanodeepSaha.jpg',company:'Rare Planet',role:'Co-founder',bio:'Co-founder of Rare Planet, building a retail and D2C business around Indian handicrafts.'},
'Sagar J Daryani':{linkedin:'https://in.linkedin.com/in/sagar-j-daryani-950085b7',photo:'https://etimg.etb2bimg.com/authorthumb/479263700.cms?height=250&imgsize=26386&width=250',company:'Wow! Momo',role:'Co-founder & CEO',bio:'Co-founder & CEO of Wow! Momo, building a Kolkata-born food and consumer brand.'},
'Sujay Santra':{linkedin:'https://in.linkedin.com/in/sujay-santra-ikure',photo:'https://images.yourstory.com/cs/wordpress/2013/10/sujay_santra_20130831.jpg?auto=format&fm=png',company:'iKure',role:'Founder & CEO',bio:'Founder & CEO of iKure, focused on technology-enabled primary healthcare.'},
'Tinku Acharya':{linkedin:'https://in.linkedin.com/in/tinkuacharya',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/Tinku_Acharya_-_Kolkata_2015-03-27_4650.JPG',company:'Videonetics',role:'Founder & Chairman',bio:'Founder of Videonetics and a technologist working across AI and video intelligence.'},
'Vineet Patawari':{linkedin:'https://in.linkedin.com/in/vineet-patawari',photo:'https://d24uab5gycr2uz.cloudfront.net/uploads/white_theme/images/about_us/founder_img2.webp',company:'Elearnmarkets / StockEdge',role:'Co-founder',bio:'Co-founder of Elearnmarkets and StockEdge, focused on financial-market education and technology.'},
'Vivek Bajaj':{linkedin:'https://in.linkedin.com/in/vbajaj',photo:'https://d24uab5gycr2uz.cloudfront.net/uploads/white_theme/images/about_us/founder_img1.webp',company:'Elearnmarkets / StockEdge',role:'Founder',bio:'Entrepreneur behind Elearnmarkets and StockEdge, focused on financial education and market technology.'}}
const split=v=>String(v||'').split(/\s*,\s*|\s+and\s+|\s*\+\s*co-?founders?/i).map(x=>x.replace(/\s*\([^)]*\)/g,'').trim()).filter(x=>x&&x.length>2&&!/^(unknown|co-founder|founder)$/i.test(x))
const avatar=(n,l,p)=>p||'https://api.dicebear.com/9.x/initials/svg?seed='+encodeURIComponent(n)
export default function FoundersPage({startups=[]}){
 const[q,setQ]=useState(''),[sector,setSector]=useState(''),[selected,setSelected]=useState(null)
 const founders=useMemo(()=>{const m=new Map();startups.forEach(s=>split(s.founder).forEach(n=>{const k=n.toLowerCase(),p=m.get(k)||{name:n,companies:[],sectors:[]};if(!p.companies.some(c=>c.name===s.name))p.companies.push({name:s.name,sector:s.sector});if(s.sector&&!p.sectors.includes(s.sector))p.sectors.push(s.sector);m.set(k,p)}));Object.entries(profiles).forEach(([name,profile])=>{const k=name.toLowerCase(),p=m.get(k)||{name,companies:[],sectors:[]};if(profile.company&&!p.companies.some(c=>c.name===profile.company))p.companies.push({name:profile.company,sector:profile.sector||'Other'});if(profile.sector&&!p.sectors.includes(profile.sector))p.sectors.push(profile.sector);m.set(k,p)});return [...m.values()].map(p=>({...p,...(profiles[p.name]||{}),bio:(profiles[p.name]||{}).bio||p.name+' is listed as a founder in the Kolkata startup ecosystem. Profile enrichment is in progress.'})).sort((a,b)=>a.name.localeCompare(b.name))},[startups])
 const sectors=[...new Set(founders.flatMap(f=>f.sectors))].sort(),filtered=founders.filter(f=>(!q||(f.name+' '+f.companies.map(c=>c.name)+' '+f.sectors+' '+f.bio).toLowerCase().includes(q.toLowerCase()))&&(!sector||f.sectors.includes(sector)))
 return <div className="founders-page"><header className="founders-topbar"><a className="founders-brand" href="/kolkata-startup-map/"><span className="brand-mark">K</span><span><b>Kolkata Startup Map</b><small>Startups · Companies · Jobs · Ecosystem</small></span></a><nav><a href="/kolkata-startup-map/startups/">Directory</a><a className="active" href="/kolkata-startup-map/foundersandceos/">Founders</a><a href="/kolkata-startup-map/jobs/">Jobs</a><a href="/kolkata-startup-map/news/">News</a></nav></header>
 <main><section className="founders-hero"><div><div className="founders-kicker">KOLKATA STARTUP MAP · FOUNDERS & CEOs</div><h1>People behind<br/><em>the companies.</em></h1><p>A visual directory of founders building startups and businesses connected to Kolkata. Click a profile to read more about the person, their company and their public links.</p></div><div className="founders-stat"><strong>{founders.length}</strong><span>founders currently indexed</span></div></section>
 <section className="founders-toolbar"><div className="founders-search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search founders, companies or sectors…"/></div><select value={sector} onChange={e=>setSector(e.target.value)}><option value="">All sectors</option>{sectors.map(x=><option key={x}>{x}</option>)}</select><span className="founders-count">{filtered.length} profiles</span></section>
 <section className="founder-grid">{filtered.map(f=><article className="founder-card" key={f.name} onClick={()=>setSelected(f)}><img src={avatar(f.name,f.linkedin,f.photo)} alt={f.name+' portrait'} loading="lazy" onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src='https://api.dicebear.com/9.x/initials/svg?seed='+encodeURIComponent(f.name)}} style={{objectPosition:f.name==='Tinku Acharya'?'50% 42%':'center center'}}/><div className="founder-card-body"><div className="founder-card-overlay"><div className="founder-card-brand">KOLKATA STARTUP MAP</div><div className="founder-card-label">FOUNDERS & CEOs</div></div><div className="founder-card-copy"><div className="founder-role">{f.companies.slice(0,2).map(c=>c.name).join(' · ')}</div><h2>{f.name}</h2><p>{f.bio}</p><div className="founder-tags">{f.sectors.slice(0,3).map(x=><span key={x}>{x}</span>)}</div></div><div className="founder-actions">{f.linkedin?<a href={f.linkedin} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>LinkedIn ↗</a>:<a href={'https://www.linkedin.com/search/results/people/?keywords='+encodeURIComponent(f.name)} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>Find on LinkedIn ↗</a>}<button>View profile →</button></div></div></article>)}</section>
 <div className="founders-note">Direct LinkedIn links are shown only for profiles verified during enrichment. Other founders use a LinkedIn people search until a direct profile is confirmed.</div></main>
 {selected&&<div className="founder-modal-backdrop" onClick={()=>setSelected(null)}><article className="founder-modal" onClick={e=>e.stopPropagation()}><button className="founder-close" onClick={()=>setSelected(null)}>×</button><img src={avatar(selected.name,selected.linkedin,selected.photo)} alt={selected.name+' portrait'} onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src='https://api.dicebear.com/9.x/initials/svg?seed='+encodeURIComponent(selected.name)}} style={{objectPosition:selected.name==='Tinku Acharya'?'50% 42%':'center center'}}/><div className="founder-detail-copy"><div className="founder-role">KOLKATA FOUNDER</div><h2>{selected.name}</h2><div className="founder-detail-location">Based in Kolkata · Public profile</div><p>{selected.bio}</p><h3>Building</h3>{selected.companies.map(c=><div className="founder-company" key={c.name}><b>{c.name}</b><span>{c.sector}</span></div>)}<div className="founder-modal-links">{selected.linkedin?<a href={selected.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a>:<a href={'https://www.linkedin.com/search/results/people/?keywords='+encodeURIComponent(selected.name)} target="_blank" rel="noreferrer">Find on LinkedIn ↗</a>}</div></div></article></div>}</div>
}