import {useEffect,useMemo,useState} from 'react'
import './founders.css'
const profiles={
'Anooshka Soham Bathwal':{linkedin:'https://in.linkedin.com/in/anooshkasohambathwal',photo:'https://dhanvesttor.com/wp-content/uploads/2025/02/Anooshka-Soham-Bathwal-CEO-Founder-of-Dhanvesttor.jpg',company:'Dhanvesttor',role:'Founder & CEO',bio:'Founder & CEO of Dhanvesttor, a Kolkata-based wealth-management firm focused on making women more confident in finance.'},
'Gaurav Jalan':{linkedin:'https://in.linkedin.com/in/gauravjalan',photo:'https://cdn.mpokket.in/leadership_2_3d8f843f31.png',company:'mPokket',role:'Founder & CEO',bio:'Founder & CEO of mPokket, a Kolkata-based fintech platform.'},
'Prabir Sarkar':{linkedin:'https://www.linkedin.com/search/results/people/?keywords=Prabir%20Sarkar%20DSMenu',photo:'https://unavatar.io/https://www.linkedin.com/in/prabirsarkar/',company:'DSMenu',role:'Founder',bio:'Founder of DSMenu, a Kolkata-based digital-menu and signage SaaS platform.'},
'Ranodeep Saha':{linkedin:'https://in.linkedin.com/in/ranodeep-saha-rareplanet',photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6MTk2MzIsInB1ciI6ImJsb2JfaWQifX0%3D--974a2d34653a958b2975a48dd8868e3a285abc1b/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJqcGVnIiwiY3JvcCI6WzAsMCw4MDAsODAwXSwicmVzaXplX3RvX2xpbWl0IjpbNjQwLDY0MF19LCJwdXIiOiJ2YXJpYXRpb24ifX0%3D--c891a9d5dd03dbf09321e28da945d51834d93c3d/Ranodeep.jpeg',company:'Rare Planet',role:'Co-founder',bio:'Co-founder of Rare Planet, building a retail and D2C business around Indian handicrafts.'},
'Sagar J Daryani':{linkedin:'https://in.linkedin.com/in/sagar-j-daryani-950085b7',photo:'https://etimg.etb2bimg.com/authorthumb/479263700.cms?height=250&imgsize=26386&width=250',company:'Wow! Momo',role:'Co-founder & CEO',bio:'Co-founder & CEO of Wow! Momo, building a Kolkata-born food and consumer brand.'},
'Sujay Santra':{linkedin:'https://in.linkedin.com/in/sujay-santra-ikure',photo:'https://images.yourstory.com/cs/wordpress/2013/10/sujay_santra_20130831.jpg?auto=format&fm=png',company:'iKure',role:'Founder & CEO',bio:'Founder & CEO of iKure, focused on technology-enabled primary healthcare.'},
'Tinku Acharya':{linkedin:'https://in.linkedin.com/in/tinkuacharya',photo:'https://commons.wikimedia.org/wiki/Special:FilePath/Tinku_Acharya_-_Kolkata_2015-03-27_4650.JPG',company:'Videonetics',role:'Founder & Chairman',bio:'Founder of Videonetics and a technologist working across AI and video intelligence.'},
'Vineet Patawari':{linkedin:'https://in.linkedin.com/in/vineet-patawari',photo:'https://d24uab5gycr2uz.cloudfront.net/uploads/white_theme/images/about_us/founder_img2.webp',company:'Elearnmarkets / StockEdge',role:'Co-founder',bio:'Co-founder of Elearnmarkets and StockEdge, focused on financial-market education and technology.'},
'Vivek Bajaj':{linkedin:'https://in.linkedin.com/in/vbajaj',photo:'https://d24uab5gycr2uz.cloudfront.net/uploads/white_theme/images/about_us/founder_img1.webp',company:'Elearnmarkets / StockEdge',role:'Founder',bio:'Entrepreneur behind Elearnmarkets and StockEdge, focused on financial education and market technology.'},
'Soumita Basu':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6MjAwNjcsInB1ciI6ImJsb2JfaWQifX0%3D--05a2c79b38dd496c4003e9ef6c8a2d4c27ba4225/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsMCw1NjAsNTYwXSwicmVzaXplX3RvX2xpbWl0IjpbNjQwLDY0MF19LCJwdXIiOiJ2YXJpYXRpb24ifX0%3D--dad9048d8c1f89e7406bae38b3b6a433a4d08475/Soumita.jpeg',company:'Zyenika Inclusive Fashion',role:'Founder & CEO',bio:'Founder & CEO of Zyenika Inclusive Fashion, a Kolkata-based inclusive fashion venture.'},
'Sujata Chatterjee':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6MjAwNTEsInB1ciI6ImJsb2JfaWQifX0%3D--f5082f4f74eb08655ad09d99d22fcae78e553f73/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsMCwxMDgwLDEwODBdLCJyZXNpemVfdG9fbGltaXQiOls2NDAsNjQwXX0sInB1ciI6InZhcmlhdGlvbiJ9fQ%3D%3D--e3a1005fa832342f20d72d4f428138e92a5924e4/Sujata%20Kolkata.png',company:'Twirl.store',role:'Founder & MD',bio:'Founder & MD of Twirl.store, a Kolkata-based fashion venture.'},
'Pauline Laravoire':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6MTk3NTgsInB1ciI6ImJsb2JfaWQifX0%3D--e1e424404aa71d964c1940105f0d583d4c46b1b2/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsMCw4MDAsODAwXSwicmVzaXplX3RvX2xpbWl0IjpbNjQwLDY0MF19LCJwdXIiOiJ2YXJpYXRpb24ifX0%3D--3610c832762c22480d31ea63c0fcedd0bd3f3e75/Pauline.jpeg',company:'Y-East',role:'Co-Founder',bio:'Co-founder of Y-East, working on sustainability and social-impact initiatives.'},
'Sukriti Agarwal':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6MTk2NDQsInB1ciI6ImJsb2JfaWQifX0%3D--dfe1294153332c00c5bc8b5c9e0a868b840adb81/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJqcGVnIiwiY3JvcCI6WzAsMCwxNTk5LDE1OTldLCJyZXNpemVfdG9fbGltaXQiOls2NDAsNjQwXX0sInB1ciI6InZhcmlhdGlvbiJ9fQ%3D%3D--3610c832762c22480d31ea63c0fcedd0bd3f3e75/Sukriti%20Outbox.jpeg',company:'Outbox',role:'Co-Founder',bio:'Co-founder of Outbox, a Kolkata-connected venture.'},
'Aishwarya Biswas':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6MTk2MTEsInB1ciI6ImJsb2JfaWQifX0%3D--2b62bd78ff976381484d7ad5434c636c03628cd7/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJqcGVnIiwiY3JvcCI6WzAsMCw4MDAsODAwXSwicmVzaXplX3RvX2xpbWl0IjpbNjQwLDY0MF19LCJwdXIiOiJ2YXJpYXRpb24ifX0%3D--206380ca8a5802d946877830c53c5769a12aedca/Aishwarya%20Biswas.jpeg',company:'Auli Lifestyle',role:'Founder',bio:'Founder of Auli Lifestyle, a Kolkata-based beauty and wellness brand.'},
'Nihal Singh':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6MTAxMTg2LCJwdXIiOiJibG9iX2lkIn19--b8513c8fccc745f6ed020a42ba9ef4750135f721/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsMCw2NjAsNjYwXSwicmVzaXplX3RvX2xpbWl0IjpbNjQwLDY0MF19LCJwdXIiOiJ2YXJpYXRpb24ifX0%3D--f410cd7f7d6fe4283295b8d1beb0a5e96ff11423/WhatsApp%20Image%202026-07-20%20at%2000.18.14.jpg',company:'spliceAI',role:'Founder',bio:'Founder of spliceAI, an early-stage AI venture connected to Kolkata.'},
'Santanu Kabi':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6ODc3MjQsInB1ciI6ImJsb2JfaWQifX0%3D--83e1d32e4d7df03514953a14972daad182af1c65/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzE1MSwwLDc2OCw3NjhdLCJyZXNpemVfdG9fbGltaXQiOls2NDAsNjQwXX19LCJwdXIiOiJ2YXJpYXRpb24ifX0%3D--ee7b4f544a07c1b42a2a6dd03b9a159afe2525b1/20171216_172737.jpg',company:'LossToProfit AI',role:'Founder',bio:'Founder of LossToProfit AI, an AI-powered profit-intelligence product.'},
'Samya Mukherjee':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6ODc2ODksInB1ciI6ImJsb2JfaWQifX0%3D--d6792e3d0f709206cf48946aaa437e41fd0a055d/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsMywzNTAsMzUwXSwicmVzaXplX3RvX2xpbWl0IjpbNjQwLDY0MF19LCJwdXIiOiJ2YXJpYXRpb24ifX0%3D--604ceeedf5a6c39be846643438afef5fe4366bbc/Samya%20Mukherjee%20Photograph676.jpg',company:'DESK Analytical Research and Consulting Foundation',role:'Founder',bio:'Founder of DESK Analytical Research and Consulting Foundation.'},
'Subhodeep Moitra':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6ODcwMTAsInB1ciI6ImJsb2JfaWQifX0%3D--dd33b5539b69e816a413f3a446259c7fb5f1c324/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzIyLDk5LDU4MCw1ODBdLCJyZXNpemVfdG9fbGltaXQiOls2NDAsNjQwXX0sInB1ciI6InZhcmlhdGlvbiJ9fQ%3D%3D--b96ca4ba4a0b08580eb2184ae15e65c2e34343a3/IMG_20260827_143056068_HDR.jpg',company:'ShadowSyn Research',role:'Co-Founder',bio:'Co-founder of ShadowSyn Research, a research-focused venture.'},
'Ananya Shrivastava':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6ODAxNzUsInB1ciI6ImJsb2JfaWQifX0%3D--6baa9d8a975b54e6fec4e8fb1b3e2f68bec2f1e5/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsMTMsMjc3LDI3N10sInJlc2l6ZV90b19saW1pdCI6WzY0MCw2NDBdfSwicHVyIjoidmFyaWF0aW9uIn19--327c3b0dd3e53985e223c39ca2ca59a54ab0ba30/ananya-pic-aadhar.jpg',company:'Jagriq',role:'Co-Founder',bio:'Co-founder of Jagriq, an AI venture connected to Kolkata.'},
'Siddhartha Dey':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6NDYxMTEsInB1ciI6ImJsb2JfaWQifX0%3D--3db77648a6b14cb3bfee71e21e95baad2ae6c0bb/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsMCwxMDI0LDEwMjRdLCJyZXNpemVfdG9fbGltaXQiOls2NDAsNjQwXX0sInB1ciI6InZhcmlhdGlvbiJ9fQ%3D%3D--fee10a9abdac0ccd5bafe1b8ab1af7ef7280db3c/Profile%20pic.jpg',company:'Finrashi',role:'Founder',bio:'Founder of Finrashi, a Kolkata-linked fintech venture.'},
'Abhijit Sarkar':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6MTAwNDYwLCJwdXIiOiJibG9iX2lkIn19--ddc3b4130d18cec05c6f521db6a9c144537d4947/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsMCwxMDI0LDEwMjRdLCJyZXNpemVfdG9fbGltaXQiOls2NDAsNjQwXX0sInB1ciI6InZhcmlhdGlvbiJ9fQ%3D%3D--800597ff0d7ee12c6f3615aa874ffd6d02087791/Teamspace%20One.jpg',company:'Edutapxr',role:'Co-Founder',bio:'Co-founder of Edutapxr, an education-technology venture connected to Kolkata.'},
'Sourendro Banerjee':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6OTc0NTMsInB1ciI6ImJsb2JfaWQifX0%3D--7c4d981946eac8f62545c7ff3cc51a4cf26d5a72/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsMjQsMjE0LDIxNF0sInJlc2l6ZV90b19saW1pdCI6WzY0MCw2NDBdfSwicHVyIjoidmFyaWF0aW9uIn19--cf6ff6b60bd9b0cf516e0cb5a66147b991d6b8d3/Sourendro_Banerjee.jpg',company:'WEBSTEP Technologies',role:'Founder',bio:'Founder of WEBSTEP Technologies, a Kolkata-based technology company.'},
'Sanchari Sarkar':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6NjUwMjAsInB1ciI6ImJsb2JfaWQifX0%3D--e345f0adab3f1809d2bb3d750042abaee096bb24/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsMTE1LDc5NSw3OTVdLCJyZXNpemVfdG9fbGltaXQiOls2NDAsNjQwXX19LCJwdXIiOiJ2YXJpYXRpb24ifX0%3D--6bc4768c7be92a3f252b38fa6af7e1e57e61bbf5/3AD504E7-833D-4D0F-98B4-F07443132CBE.jpg',company:'Digital Platform 271',role:'Founder',bio:'Founder of Digital Platform 271.'},
'Suman Mondal':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6NjM5OTgsInB1ciI6ImJsb2JfaWQifX0%3D--0b433ba9e3c7b490309c0ee46234180670125f17/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsMTI4LDc2OCw3NjhdLCJyZXNpemVfdG9fbGltaXQiOls2NDAsNjQwXX19LCJwdXIiOiJ2YXJpYXRpb24ifX0%3D--7e55d1a44cd8d10f87a05dcc901e8c404040399f/1000101636.jpg',company:'KIDFACTORY',role:'Founder',bio:'Founder of KIDFACTORY.'},
'Rahul Pandey':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6NjI1MTgsInB1ciI6ImJsb2JfaWQifX0%3D--676923b641749217259cbe16a28a5d718912167b/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsNCw1NzYsNTc2XSwicmVzaXplX3RvX2xpbWl0IjpbNjQwLDY0MF19LCJwdXIiOiJ2YXJpYXRpb24ifX0%3D--9a4b03ae767132f359b294a4f3bd38b0de128e0d/1000277298.jpg',company:'Anteratic Labs',role:'Founder',bio:'Founder of Anteratic Labs, an early-stage technology company connected to Kolkata.'},
'Bapon Biswas':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6MzQ4NDksInB1ciI6ImJsb2JfaWQifX0%3D--3ee09e1061e83b851773346a388523eedd880440/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsMjU4LDU3OSw1NzldLCJyZXNpemVfdG9fbGltaXQiOls2NDAsNjQwXX19LCJwdXIiOiJ2YXJpYXRpb24ifX0%3D--4452cb686e4027af7f3f76d898e23ce638194aff/Screenshot_20260103-010512_1.jpg',company:'minti jemun',role:'Founder & CEO',bio:'Founder & CEO of minti jemun.'},
'Biswarup Das':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6MzQxMzgsInB1ciI6ImJsb2JfaWQifX0%3D--02ddc325beb0c8140775de810e37324062901722/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzEsMCw4NjYsODY2XSwicmVzaXplX3RvX2xpbWl0IjpbNjQwLDY0MF19LCJwdXIiOiJ2YXJpYXRpb24ifX0%3D--f8123c27b1f56860a2492f4362b0d4a0f9a46e02/Screenshot%202026-01-29%20102502.jpg',company:'Hexical AI',role:'Founder',bio:'Founder of Hexical AI.'},
'Mehul Joisar':{photo:'https://echai.ventures/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsiZGF0YSI6NDQ4MCwicHVyIjoiYmxvYl9pZCJ9fQ%3D%3D--5dd341dc4f3fdce46270bc3ce8e12a0c14d7cc5d/eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJ3ZWJwIiwiY3JvcCI6WzAsMTAwLDQwMCw0MDBdLCJyZXNpemVfdG9fbGltaXQiOls2NDAsNjQwXX19LCJwdXIiOiJ2YXJpYXRpb24ifX0%3D--4b7d77d40e57ac8c622fae0c81fb57974b3a5fa3/Profile%20pic%20400x600.jpg',company:'Digicians',role:'Founder',bio:'Founder of Digicians.'}
}
const split=v=>String(v||'').split(/\s*,\s*|\s+and\s+|\s*\+\s*co-?founders?/i).map(x=>x.replace(/\s*\([^)]*\)/g,'').trim()).filter(x=>x&&x.length>2&&!/^(unknown|co-founder|founder)$/i.test(x))
const avatar=(n,l,p,map={})=>map[n]||p||'https://api.dicebear.com/9.x/initials/svg?seed='+encodeURIComponent(n)
export default function FoundersPage({startups=[]}){
 const[q,setQ]=useState(''),[sector,setSector]=useState(''),[selected,setSelected]=useState(null),[imageMap,setImageMap]=useState({})
 useEffect(()=>{fetch('/kolkata-startup-map/founder-images/manifest.json').then(r=>r.ok?r.json():{}).then(setImageMap).catch(()=>{})},[])
 const founders=useMemo(()=>{const m=new Map();startups.forEach(s=>split(s.founder).forEach(n=>{const k=n.toLowerCase(),p=m.get(k)||{name:n,companies:[],sectors:[]};if(!p.companies.some(c=>c.name===s.name))p.companies.push({name:s.name,sector:s.sector});if(s.sector&&!p.sectors.includes(s.sector))p.sectors.push(s.sector);m.set(k,p)}));Object.entries(profiles).forEach(([name,profile])=>{const k=name.toLowerCase(),p=m.get(k)||{name,companies:[],sectors:[]};if(profile.company&&!p.companies.some(c=>c.name===profile.company))p.companies.push({name:profile.company,sector:profile.sector||'Other'});if(profile.sector&&!p.sectors.includes(profile.sector))p.sectors.push(profile.sector);m.set(k,p)});return [...m.values()].map(p=>({...p,...(profiles[p.name]||{}),bio:(profiles[p.name]||{}).bio||p.name+' is listed as a founder in the Kolkata startup ecosystem. Profile enrichment is in progress.'})).sort((a,b)=>a.name.localeCompare(b.name))},[startups])
 const sectors=[...new Set(founders.flatMap(f=>f.sectors))].sort(),filtered=founders.filter(f=>(!q||(f.name+' '+f.companies.map(c=>c.name)+' '+f.sectors+' '+f.bio).toLowerCase().includes(q.toLowerCase()))&&(!sector||f.sectors.includes(sector)))
 return <div className="founders-page"><header className="founders-topbar"><a className="founders-brand" href="/kolkata-startup-map/"><span className="brand-mark">K</span><span><b>Kolkata Startup Map</b><small>Startups · Companies · Jobs · Ecosystem</small></span></a><nav><a href="/kolkata-startup-map/startups/">Directory</a><a className="active" href="/kolkata-startup-map/foundersandceos/">Founders</a><a href="/kolkata-startup-map/jobs/">Jobs</a><a href="/kolkata-startup-map/news/">News</a></nav></header>
 <main><section className="founders-hero"><div><div className="founders-kicker">KOLKATA STARTUP MAP · FOUNDERS & CEOs</div><h1>People behind<br/><em>the companies.</em></h1><p>A visual directory of founders building startups and businesses connected to Kolkata. Click a profile to read more about the person, their company and their public links.</p></div><div className="founders-stat"><strong>{founders.length}</strong><span>founders currently indexed</span></div></section>
 <section className="founders-toolbar"><div className="founders-search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search founders, companies or sectors…"/></div><select value={sector} onChange={e=>setSector(e.target.value)}><option value="">All sectors</option>{sectors.map(x=><option key={x}>{x}</option>)}</select><span className="founders-count">{filtered.length} profiles</span></section>
 <section className="founder-grid">{filtered.map(f=><article className="founder-card" key={f.name} onClick={()=>setSelected(f)}><img src={avatar(f.name,f.linkedin,f.photo,imageMap)} alt={f.name+' portrait'} loading="lazy" onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src='https://api.dicebear.com/9.x/initials/svg?seed='+encodeURIComponent(f.name)}} style={{objectPosition:f.name==='Tinku Acharya'?'50% 42%':'center center'}}/><div className="founder-card-body"><div className="founder-card-overlay"><div className="founder-card-brand">KOLKATA STARTUP MAP</div><div className="founder-card-label">FOUNDERS & CEOs</div></div><div className="founder-card-copy"><div className="founder-role">{f.companies.slice(0,2).map(c=>c.name).join(' · ')}</div><h2>{f.name}</h2><p>{f.bio}</p><div className="founder-tags">{f.sectors.slice(0,3).map(x=><span key={x}>{x}</span>)}</div></div><div className="founder-actions">{f.linkedin?<a href={f.linkedin} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>LinkedIn ↗</a>:<a href={'https://www.linkedin.com/search/results/people/?keywords='+encodeURIComponent(f.name)} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>Find on LinkedIn ↗</a>}<button>View profile →</button></div></div></article>)}</section>
 <div className="founders-note">Direct LinkedIn links are shown only for profiles verified during enrichment. Other founders use a LinkedIn people search until a direct profile is confirmed.</div></main>
 {selected&&<div className="founder-modal-backdrop" onClick={()=>setSelected(null)}><article className="founder-modal" onClick={e=>e.stopPropagation()}><button className="founder-close" onClick={()=>setSelected(null)}>×</button><img src={avatar(selected.name,selected.linkedin,selected.photo,imageMap)} alt={selected.name+' portrait'} onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src='https://api.dicebear.com/9.x/initials/svg?seed='+encodeURIComponent(selected.name)}} style={{objectPosition:selected.name==='Tinku Acharya'?'50% 42%':'center center'}}/><div className="founder-detail-copy"><div className="founder-role">KOLKATA FOUNDER</div><h2>{selected.name}</h2><div className="founder-detail-location">Based in Kolkata · Public profile</div><p>{selected.bio}</p><h3>Building</h3>{selected.companies.map(c=><div className="founder-company" key={c.name}><b>{c.name}</b><span>{c.sector}</span></div>)}<div className="founder-modal-links">{selected.linkedin?<a href={selected.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a>:<a href={'https://www.linkedin.com/search/results/people/?keywords='+encodeURIComponent(selected.name)} target="_blank" rel="noreferrer">Find on LinkedIn ↗</a>}</div></div></article></div>}</div>
}